server:
  port: 8443
spring:
  datasource:
    username: root
    password: 111111
    # serverTimezone=UTC 解决时区问题
    url: jdbc:mysql://localhost:3306/main?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    # mysql8 以上使用 cj
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: null
    database-platform: org.hibernate.dialect.MySQLDialect